services:
  app:
    build:
      context: ./app
    ports:
      - "4743:4743"
    networks:
      - db_network
      - site_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4743/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5655:3306"
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: ./nginx
    ports:
      - "5423:824"
    networks:
      - site_network
    depends_on:
      - app

volumes:
  db_volume:

networks:
  db_network:
  site_network:
